[project]
name = "twinapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.143.0",
    "openai>=3.26.1",
    "pydantic>=2.14.0",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "uvicorn>=0.34.0",
]
